### ISSUE TITLE
Flash light icon not showin in Android device

### ISSUE THREAD

**Issue by gopalmak** [nateshmbhat/card-scanner-flutter#81]

**Comment by nateshmbhat** [comment]
Hi @gopalmak 👋

A fix for this issue has been submitted in PR #89, which adds a flashlight toggle button to the Android scanner UI. Could you please test it by pointing your `pubspec.yaml` directly to the PR branch?

```yaml
dependencies:
  card_scanner:
    git:
      url: https://github.com/nateshmbhat/card-scanner-flutter.git
      ref: fix/issues-58-70-81-86-88
```

Please report back here if you encounter any issues or if the fix works as expected. Your feedback would be greatly appreciated before merging! 🙏

---
_Generated by [Claude Code](https://claude.ai/code)_
